context:
  version: "7.1.0"

package:
  name: webpack-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/webpack-cli/-/webpack-cli-${{ version }}.tgz
  sha256: ce0f6c8da92399001607861232e9a7523469b200ae4585c730807c1a9db9cc78

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - webpack-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A bundler for javascript and friends.
  homepage: https://github.com/webpack/webpack-cli
  repository: https://github.com/webpack/webpack-cli

extra:
  recipe-maintainers:
    - danielnachun
